version: '2'

services:
  nginx:
    build: ./atlassian-proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - jira
      - confluence
      - crowd
      - bamboo

  jira:
    build: ./atlassian-jira
    links:
      - db
    volumes:
      - atlassian-jira-volume:/var/atlassian/jira
    expose:
      - "8080"
    environment:
      - JIRA_JDBC_USER = jira
      - JIRA_JDBC_PASSWORD = jira
      - JIRA_JDBC_URL = jdbc:postgresql://db:5432/jira

  confluence:
    build: ./atlassian-confluence
    links:
      - db
    volumes:
      - atlassian-confluence-volume:/var/atlassian/confluence
    expose:
      - "8090"

  bamboo:
    build: ./atlassian-bamboo
    links:
      - db
    volumes:
      - atlassian-bamboo-volume:/var/atlassian/bamboo
    expose:
      - "8085"

  crowd:
    build: ./atlassian-crowd
    links:
      - db
    volumes:
      - atlassian-crowd-volume:/var/atlassian/crowd
    expose:
      - "8095"

  db:
    build: ./atlassian-database
    volumes:
      - postgres-volume:/var/lib/postgresql

volumes:
  atlassian-jira-volume:
    driver: local

  atlassian-bamboo-volume:
    driver: local

  atlassian-confluence-volume:
    driver: local

  atlassian-crowd-volume:
    driver: local

  postgres-volume:
    driver: local
