version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - jira
      - confluence
      - crowd
      - bamboo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  jira:
    build: ./atlassian-jira
    restart: always
    links:
      - db
    volumes:
      - atlassian-volume:/var/atlassian/jira
    expose:
      - "8080"

  confluence:
    build: ./atlassian-confluence
    restart: always
    links:
      - db
    volumes:
      - atlassian-volume:/var/atlassian/confluence
    expose:
      - "8085"

  bamboo:
    build: ./atlassian-bamboo
    restart: always
    links:
      - db
    volumes:
      - atlassian-volume:/var/atlassian/bamboo
    expose:
      - "8090"

  crowd:
    build: ./atlassian-crowd
    restart: always
    links:
      - db
    volumes:
      - atlassian-volume:/var/atlassian/crowd
    expose:
      - "8095"

  db:
    build: ./postgres
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql

volumes:
  atlassian-volume:
    driver: local

  postgres-volume:
    driver: local
